(package "kaomoji.el"
         "0.1.0"
         "Input kaomoji superb easily")

(website-url "https://github.com/elp-revive/kaomoji.el")
(keywords "tools" "fun")

(package-file "kaomoji.el")
(files "kaomoji-data.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
